/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ApiAgentPairRouteImport } from './routes/api/agent/pair'
import { Route as ApiPublicAgentRouteImport } from './routes/api/public/agent'
import { Route as ApiPublicAgentPairRouteImport } from './routes/api/public/agent/pair'
import { Route as ApiPublicAgentRelayRouteImport } from './routes/api/public/agent/relay'
import { Route as ApiPublicApiAgentPairRouteImport } from './routes/api/public/api/agent/pair'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentPairRoute = ApiAgentPairRouteImport.update({
  id: '/api/agent/pair',
  path: '/api/agent/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentRoute = ApiPublicAgentRouteImport.update({
  id: '/api/public/agent',
  path: '/api/public/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentPairRoute = ApiPublicAgentPairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => ApiPublicAgentRoute,
} as any)
const ApiPublicAgentRelayRoute = ApiPublicAgentRelayRouteImport.update({
  id: '/relay',
  path: '/relay',
  getParentRoute: () => ApiPublicAgentRoute,
} as any)
const ApiPublicApiAgentPairRoute = ApiPublicApiAgentPairRouteImport.update({
  id: '/api/public/api/agent/pair',
  path: '/api/public/api/agent/pair',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/api/agent/pair': typeof ApiAgentPairRoute
  '/api/public/agent': typeof ApiPublicAgentRouteWithChildren
  '/api/public/agent/pair': typeof ApiPublicAgentPairRoute
  '/api/public/agent/relay': typeof ApiPublicAgentRelayRoute
  '/api/public/api/agent/pair': typeof ApiPublicApiAgentPairRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/api/agent/pair': typeof ApiAgentPairRoute
  '/api/public/agent': typeof ApiPublicAgentRouteWithChildren
  '/api/public/agent/pair': typeof ApiPublicAgentPairRoute
  '/api/public/agent/relay': typeof ApiPublicAgentRelayRoute
  '/api/public/api/agent/pair': typeof ApiPublicApiAgentPairRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/api/agent/pair': typeof ApiAgentPairRoute
  '/api/public/agent': typeof ApiPublicAgentRouteWithChildren
  '/api/public/agent/pair': typeof ApiPublicAgentPairRoute
  '/api/public/agent/relay': typeof ApiPublicAgentRelayRoute
  '/api/public/api/agent/pair': typeof ApiPublicApiAgentPairRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/auth'
    | '/dashboard'
    | '/api/agent/pair'
    | '/api/public/agent'
    | '/api/public/agent/pair'
    | '/api/public/agent/relay'
    | '/api/public/api/agent/pair'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent'
    | '/auth'
    | '/dashboard'
    | '/api/agent/pair'
    | '/api/public/agent'
    | '/api/public/agent/pair'
    | '/api/public/agent/relay'
    | '/api/public/api/agent/pair'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/auth'
    | '/dashboard'
    | '/api/agent/pair'
    | '/api/public/agent'
    | '/api/public/agent/pair'
    | '/api/public/agent/relay'
    | '/api/public/api/agent/pair'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  ApiAgentPairRoute: typeof ApiAgentPairRoute
  ApiPublicAgentRoute: typeof ApiPublicAgentRouteWithChildren
  ApiPublicApiAgentPairRoute: typeof ApiPublicApiAgentPairRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/pair': {
      id: '/api/agent/pair'
      path: '/api/agent/pair'
      fullPath: '/api/agent/pair'
      preLoaderRoute: typeof ApiAgentPairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent': {
      id: '/api/public/agent'
      path: '/api/public/agent'
      fullPath: '/api/public/agent'
      preLoaderRoute: typeof ApiPublicAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/pair': {
      id: '/api/public/agent/pair'
      path: '/pair'
      fullPath: '/api/public/agent/pair'
      preLoaderRoute: typeof ApiPublicAgentPairRouteImport
      parentRoute: typeof ApiPublicAgentRoute
    }
    '/api/public/agent/relay': {
      id: '/api/public/agent/relay'
      path: '/relay'
      fullPath: '/api/public/agent/relay'
      preLoaderRoute: typeof ApiPublicAgentRelayRouteImport
      parentRoute: typeof ApiPublicAgentRoute
    }
    '/api/public/api/agent/pair': {
      id: '/api/public/api/agent/pair'
      path: '/api/public/api/agent/pair'
      fullPath: '/api/public/api/agent/pair'
      preLoaderRoute: typeof ApiPublicApiAgentPairRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiPublicAgentRouteChildren {
  ApiPublicAgentPairRoute: typeof ApiPublicAgentPairRoute
  ApiPublicAgentRelayRoute: typeof ApiPublicAgentRelayRoute
}

const ApiPublicAgentRouteChildren: ApiPublicAgentRouteChildren = {
  ApiPublicAgentPairRoute: ApiPublicAgentPairRoute,
  ApiPublicAgentRelayRoute: ApiPublicAgentRelayRoute,
}

const ApiPublicAgentRouteWithChildren = ApiPublicAgentRoute._addFileChildren(
  ApiPublicAgentRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  ApiAgentPairRoute: ApiAgentPairRoute,
  ApiPublicAgentRoute: ApiPublicAgentRouteWithChildren,
  ApiPublicApiAgentPairRoute: ApiPublicApiAgentPairRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
